# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Half-Life 2: VR"
email: team@halflife2vr.com
name: Source VR Mod Team
description: >- # this means to ignore newlines until "baseurl:"
  Half Life 2: VR is a third-party mod for the 2004 PC gaming classic by
  Valve Software. It allows players to experience the world of Half Life 2
  in virtual reality.
twitter_username: username
github_username: hl2vr
minimal_mistakes_skin: dark
locale: en
search: false

url: "https://halflife2vr.com"
repository: "hl2vr/hl2vr.github.io"
logo: "/assets/images/game.ico"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /news/page:num
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Source VR Mod Team"
  avatar : "/assets/images/game.ico"
  bio    : "We are a group of VR enthusiasts working on bringing Half-Life 2 to VR."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://halflife2vr.com"

footer:
  links:
    #- label: "Steam"
    #  icon: "fab fa-fw fa-steam"
    #  url: "https://store.steampowered.com/app/658920/HalfLife_2_VR/"
    - label: "Reddit"
      icon: "fab fa-fw fa-reddit"
      url: "https://reddit.com/r/hlvr/"
    - label: "Discord"
      icon: "fab fa-fw fa-discord"
      url: "http://flat2vr.com/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: true
      comments: true
      share: true
      related: true
      header:
        image: /assets/images/title.png
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      header:
        image: /assets/images/title.png

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
